refactor: move helmet middlewares to top app
htmlacademy-nodejs/809375-typoteka-3 pull request #20
Opened 2021-05-11 10:25 UTC by Shramkoweb

2021-05-16 14:42 UTC, Shramkoweb commented on src/service/api/users/users.service.js
> +    console.log(userData, `userData`);
Remember to delete

2021-05-16 14:42 UTC, Shramkoweb commented on src/service/api/users/users.service.js
> +    const rawUser = user.get();
Maybe better to use destructorisation ?

2021-06-01 21:36 UTC, html-malex requested changes
1. небольшое замечание
2. по заданию: `Напишите все необходимые тесты для проверки работоспособности нового обработчика маршрута.`

2021-06-01 21:36 UTC, html-malex commented on src/service/api/users/users.validators.js
> +    console.log(err);
Здесь, наверно, тоже стоит пользователю вернуть какой-то статус?

2021-06-05 09:15 UTC, html-malex approved these changes

2021-06-05 09:15 UTC, merged